trigger:
  - main  # Runs the pipeline when code is pushed

pool:
  name: Azure-VM-Pipeline  # Use your self-hosted agent

steps:
  # Step 1: Set up IIS and create the website
  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      EnableIIS: true
      IISDeploymentType: 'IISWebsite'
      ActionIISWebsite: 'CreateOrUpdateWebsite'
      WebsiteName: 'LT Foto'
      WebsitePhysicalPath: 'C:\inetpub\wwwroot'
      WebsiteAuthUserName: 'adminuser'
      WebsiteAuthUserPassword: 'Welcome@1234'

  # Step 2: Copy HTML files to the staging directory
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'  # Copy the HTML files
      Contents: '**'  # Copy everything inside the folder
      TargetFolder: '$(Build.ArtifactStagingDirectory)/html-site'

  # Step 3: Publish the HTML site as an artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/html-site'
      artifactName: 'html-site'

  # Step 4: Deploy the files to the Azure VM using WinRM
  - task: WindowsMachineFileCopy@2
    inputs:
      SourcePath: '$(Build.ArtifactStagingDirectory)/html-site'
      MachineNames: '172.190.137.198'  # Replace with your VM's Private IP if needed
      AdminUserName: 'adminuser'
      AdminPassword: 'Welcome@1234'
      TargetPath: 'winrm://172.190.137.198'  # ✅ Using WinRM instead of SMB
      cleanTargetBeforeCopy: true  # Clears old files before copying new ones
      Overwrite: true
