trigger:
  - main  # Runs the pipeline when code is pushed

pool:
  name: Azure-VM-Pipeline  # Use your self-hosted agent

steps:
  # Step 1: Set up IIS and create the website
  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      EnableIIS: true
      IISDeploymentType: 'IISWebsite'
      ActionIISWebsite: 'CreateOrUpdateWebsite'
      WebsiteName: 'LT Foto'
      WebsitePhysicalPath: 'C:\inetpub\wwwroot'
      WebsiteAuthUserName: 'adminuser'
      WebsiteAuthUserPassword: 'Welcome@1234'

  # Step 2: Copy HTML files to the staging directory
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'  # Copy the HTML files
      Contents: '**'  # Copy everything inside the folder
      TargetFolder: '$(Build.ArtifactStagingDirectory)/html-site'

  # Step 3: Publish the HTML site as an artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/html-site'
      artifactName: 'html-site'

  # Step 4: Move the files to IIS wwwroot (Fix for local file transfer)
  - task: PowerShell@2
    displayName: 'Move files to IIS wwwroot'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Moving files to IIS wwwroot..."
        Copy-Item -Path "C:\agents\_work\1\a\html-site\*" -Destination "C:\inetpub\wwwroot\" -Recurse -Force
        Write-Host "Files copied successfully!"
